"""
payment admin page generated by template

template author: Meng Zhao fortable1999@gmail.com
"""

from django.contrib import admin
from payment.models import Payment


class PaymentAdmin(admin.ModelAdmin):
	"""docstring for PaymentAdmin"""
	list_display = (
		'text', 
		'created_datetime',
		'updated_datetime',
	)
		

admin.site.register(Payment, PaymentAdmin)
