
# User could change this
PAYPAL_SECURITY_USERID = ""
PAYPAL_SECURITY_PASSWORD = ""
PAYPAL_SECURITY_SIGNATURE = ""
PAYPAL_REQUEST_DATA_FORMAT = "JSON"
PAYPAL_RESPONSE_DATA_FORMAT = "JSON"
PAYPAL_APPLICATION_ID = ""
