"""
payment url configure generated by template

template author: Meng Zhao fortable1999@gmail.com
"""

from django.conf.urls import patterns, include, url
from payment import views as payment_views

urlpatterns = patterns(
    '',

    #
    # A Basic CRUD function for Payment model
    #
    # List all objects of Payment
    url(r'^$',
        payment_views.PaymentListView.as_view(),
        name="payment_list"),

    # Create new object of Payment
    url(r'^create$',
        payment_views.PaymentCreateView.as_view(),
        name="payment_create"),

    # Delete an object of Payment
    url(r'^(?P<pk>[a-z0-9A-Z]+)/delete$',
        payment_views.PaymentDeleteView.as_view(),
        name="payment_delete"),

    # Update an object of Payment
    url(r'^(?P<pk>[a-z0-9A-Z]+)/update$',
        payment_views.PaymentUpdateView.as_view(),
        name="payment_update"),

    # Details of a object of Payment
    url(r'^(?P<pk>[a-z0-9A-Z]+)$',
        payment_views.PaymentDetailView.as_view(),
        name="payment_detail"),

)

