"""
payment views generated by template

template author: Meng Zhao fortable1999@gmail.com

A basic CRUD viewset is defined.
"""

from django.core.urlresolvers import reverse_lazy as reverse
from django.views.generic import ListView, CreateView, DetailView, DeleteView, UpdateView
from django.shortcuts import render

from payment.models import Payment
from payment.forms import PaymentModelForm


class PaymentListView(ListView):
	template_name = "payment/list.html"
	model = Payment


class PaymentCreateView(CreateView):
	template_name = "payment/create.html"
	form_class = PaymentModelForm

	def get_success_url(self):
		return reverse('payment_detail', kwargs={'pk': self.object.id})


class PaymentDetailView(DetailView):
	template_name = "payment/detail.html"
	model = Payment


class PaymentDeleteView(DeleteView):
	template_name = "payment/delete.html"
	form_class = PaymentModelForm
	model = Payment

	def get_success_url(self):
		return reverse('payment_list')


class PaymentUpdateView(UpdateView):
	template_name = "payment/update.html"
	form_class = PaymentModelForm
	model = Payment

	def get_success_url(self):
		return reverse('payment_detail', kwargs={'pk': self.object.id})
