"""
payment test cases generated by template

template author: Meng Zhao fortable1999@gmail.com
"""

from django.test import TestCase
from django.core.urlresolvers import reverse

# Create your tests here.

class PaymentCRUDTestCase(TestCase):
    """
    testcases for PaymentCRUDTestCase
    """
    def setUp(self):
        pass

    def test_create_payment(self):
        """
        post to test_create_payment
        """
        response = self.client.post(
            reverse('payment_create'),
            { 
                "text": "test comment", 
            },
            follow=True,
        )
        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.context['object'].text, "test comment")
        self.assertTemplateUsed(response, 'payment/detail.html')
		
    def test_detail_payment(self):
        """
        get to test_detail_payment
        """
        pass

    def test_update_payment(self):
        """
        post to test_update_payment
        """
        pass

    def test_list_payment(self):
        """
        get to test_list_payment
        """
        pass

    def test_delete_payment(self):
        """
        post to test_delete_payment
        """
        pass

