"""
payment test cases generated by template

template author: Meng Zhao fortable1999@gmail.com
"""

import datetime

from django.test import TestCase
from django.core.urlresolvers import reverse
from payment.models import PayPalRestAPIMixin
from django.contrib.sites.models import Site

class TestPaypalRestAPIClass(PayPalRestAPIMixin):

    def __init__(self, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)

class PaypalPreapprovalPaymentTestCase(TestCase):
    """
    testcases for PayPal API
    """
    def setUp(self):
        self.preapproval = TestPaypalRestAPIClass(
            start_date = datetime.datetime.now() + datetime.timedelta(hours=1),
            end_date = datetime.datetime.now() + datetime.timedelta(hours=8),
        )
        site = Site.objects.get()
        site.name = "http://ouroborothon.com"
        site.domain = "http://ouroborothon.com"
        site.save()

    def test_create_preapproval_payment(self):
        print("Create a preapproval payment")
        result = self.preapproval.invoke_preapproval(
            operation="Preapproval"
        )
        print(result)
        print("Redirect to:")
        print("https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_ap-preapproval&preapprovalkey=" + result['preapprovalKey'])
        self.assertEqual(result['responseEnvelope']['ack'].lower(), "success")
        preapproval_key = result['preapprovalKey']

        result = self.preapproval.invoke_preapproval_details(
            operation="PreapprovalDetails",
            preapproval_key = preapproval_key,
        )
        print(result)
        self.assertEqual(result['responseEnvelope']['ack'].lower(), "success")

